"""Added account table

Revision ID: 77802e220e4b
Revises: 
Create Date: 2022-09-05 15:49:09.020858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77802e220e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
