"""Added is_done and is_in_progress column

Revision ID: 9c2215844f59
Revises: c87e79679ee6
Create Date: 2022-09-06 14:29:16.203161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2215844f59'
down_revision = 'c87e79679ee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
