"""Added is_done and is_in_progress column

Revision ID: c87e79679ee6
Revises: 77802e220e4b
Create Date: 2022-09-06 13:34:11.841420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87e79679ee6'
down_revision = '77802e220e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('is_in_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_in_progress')
    op.drop_column('items', 'is_done')
    # ### end Alembic commands ###
